#version 450
layout(local_size_x = 16, local_size_y = 16) in;


layout(set = 0, binding = 0) uniform sampler2D inDepth; 

layout(set = 0, binding = 1, r32f) uniform writeonly image2D outDepth;

layout(push_constant) uniform Push {
    vec2 invSize; 
} push;

void main() {
    ivec2 pos = ivec2(gl_GlobalInvocationID.xy);
    ivec2 outSize = imageSize(outDepth);
    
    if (pos.x >= outSize.x || pos.y >= outSize.y) return;
    
    
    vec2 uv = (vec2(pos) + 0.5) * (1.0 / vec2(outSize));
    
    
    
    float d1 = textureLod(inDepth, uv + vec2(-0.25, -0.25) * push.invSize, 0.0).r;
    float d2 = textureLod(inDepth, uv + vec2( 0.25, -0.25) * push.invSize, 0.0).r;
    float d3 = textureLod(inDepth, uv + vec2(-0.25,  0.25) * push.invSize, 0.0).r;
    float d4 = textureLod(inDepth, uv + vec2( 0.25,  0.25) * push.invSize, 0.0).r;
    
    
    float maxD = max(max(d1, d2), max(d3, d4));
    
    
    imageStore(outDepth, pos, vec4(maxD));
}