#version 460
layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

// SET 0: Global UBO
layout(set = 0, binding = 0) uniform GlobalUbo {
     mat4 projection; mat4 invViewProj; mat4 view; vec3 camPos; float zNear;
    vec3 sunDir; float zFar; vec4 screenSize; mat4 sunLightSpaceMatrices[4];
    vec4 cascadeSplits; uint gridDimX; uint gridDimY; uint gridDimZ; uint portalID; float lightSize;
    vec3 sunColor; float sunIntensity;
    vec4 sscsParams; vec4 gtaoParams; vec4 fogParams; vec4 fogColor; vec4 inscatterColor;
    vec4 skyZenithColor; vec4 skyHorizonColor; vec4 skySunParams;
    vec4 ssgiParams;
    vec4 rtParams;
    
    mat4 prevViewProj;
    vec4 ppExposureParams;
    vec4 ppColorBalance;
    vec4 ppBloomParams;
    vec4 ppDoFParams; 
    vec4 ppVignetteGrain;
    vec4 ppMotionBlur;
    vec4 ppLensFlare;
    vec4 ppTAA_CAS;       // ДОБАВЛЕНО
    vec4 ppLensAdvanced;  // x: halo, y: caDir, z: autoFocus, w: tonemapper
    vec4 ppDistortionDirt;
    vec4 ppDitherAniso;
    vec4 cgShadows;
    vec4 cgMidtones;
    vec4 cgHighlights;
    vec4 ppRetroParams;
    vec4 ppRetroParams2;
    vec4 ppStylizedParams;
    vec4 ppOutlineParams;
    vec4 ppOutlineColor;
    vec4 ppOutlineJitter;
       vec4 ppWeatherSSR;
    vec4 ppSSSS;
    vec4 ppWeatherParams;

    vec4 cgGlobalLift;
    vec4 cgGlobalGamma;
    vec4 cgGlobalGain;
    vec4 cgGlobalOffset;
    vec4 cgShadowsLift;
    vec4 cgShadowsGamma;
    vec4 cgShadowsGain;
    vec4 cgShadowsOffset;
    vec4 cgMidtonesLift;
    vec4 cgMidtonesGamma;
    vec4 cgMidtonesGain;
    vec4 cgMidtonesOffset;
    vec4 cgHighlightsLift;
    vec4 cgHighlightsGamma;
    vec4 cgHighlightsGain;
    vec4 cgHighlightsOffset;
    vec4 cgRgbMixerRed;
    vec4 cgRgbMixerGreen;
    vec4 cgRgbMixerBlue;
    vec4 ppBlurs;
    vec4 ppBlurCenter;
    vec4 ppColorFX;
    vec4 ppFilmDamage;
    vec4 ppEdgeDetect;
    vec4 ppEdgeDetect2;
    vec4 ppEdgeColor;
    vec4 ppEmboss;
    vec4 ppSketch;
    vec4 ppSketch2;
    vec4 ppHalftone; 
    vec4 ppDitherData;
    vec4 ditherShadow;
    vec4 ditherMid;
    vec4 ditherHighlight;
    vec4 ppWarp;
    vec4 ppWarp2;
    vec4 ppColorComp;
    vec4 shadowRampColor1;
    vec4 shadowRampColor2;
} ubo;

// SET 1: G-Buffer
layout(set = 1, binding = 0) uniform sampler2D gNormalRoughness;
layout(set = 1, binding = 3) uniform sampler2D gDepth;
layout(set = 1, binding = 1) uniform sampler2D gAlbedoMetallic;
// SET 2: Targets
layout(set = 2, binding = 0, rgba16f) uniform image2D hdrOutput; // Читаем и дозаписываем!
layout(set = 2, binding = 1, rgba16f) uniform readonly image2D ssgiRaw; // Наш шумный свет

// Линеаризация глубины для правильных весов
float getLinearDepth(float d) {
    return ubo.zNear * ubo.zFar / (ubo.zFar + d * (ubo.zNear - ubo.zFar));
}

void main() {
    ivec2 pixelCoords = ivec2(gl_GlobalInvocationID.xy);
    if (pixelCoords.x >= int(ubo.screenSize.x) || pixelCoords.y >= int(ubo.screenSize.y)) return;

    vec2 uv = (vec2(pixelCoords) + 0.5) / ubo.screenSize.xy;
    float centerDepthRaw = texture(gDepth, uv).r;
    
    if (centerDepthRaw >= 1.0) return; // Небо
    
    float centerDepth = getLinearDepth(centerDepthRaw);
    vec3 centerNormal = normalize(texture(gNormalRoughness, uv).xyz);

    vec3 sumColor = vec3(0.0);
    float sumWeight = 0.0;

    int radius = 2; // Ядро 5x5. Для более мощного блюра ставь 3 (7x7)
    for (int x = -radius; x <= radius; x++) {
        for (int y = -radius; y <= radius; y++) {
            ivec2 sampleCoords = clamp(pixelCoords + ivec2(x, y), ivec2(0), ivec2(ubo.screenSize.xy) - 1);
            vec2 sampleUv = (vec2(sampleCoords) + 0.5) / ubo.screenSize.xy;
            
            float sampleDepthRaw = texture(gDepth, sampleUv).r;
            float sampleDepth = getLinearDepth(sampleDepthRaw);
            vec3 sampleNormal = normalize(texture(gNormalRoughness, sampleUv).xyz);
            vec3 sampleGI = imageLoad(ssgiRaw, sampleCoords).rgb;

            // Считаем веса Билатерального фильтра
            float wSpatial = exp(-float(x*x + y*y) / (2.0 * float(radius * radius)));
            float wDepth = exp(-abs(centerDepth - sampleDepth) * 20.0); // Скачок глубины отсекает пиксель
            float wNormal = pow(max(dot(centerNormal, sampleNormal), 0.0), 32.0); // Другой угол отсекает пиксель
            
            float weight = wSpatial * wDepth * wNormal;
            sumColor += sampleGI * weight;
            sumWeight += weight;
        }
    }

    vec3 blurredGI = sumColor / max(sumWeight, 0.0001);
    
    vec3 albedo = texture(gAlbedoMetallic, uv).rgb; // Берем диффуз, чтобы покрасить отскоки
    
    vec3 directLight = imageLoad(hdrOutput, pixelCoords).rgb;
    
    // Добавляем очищенный непрямой свет к прямому свету сцены
    imageStore(hdrOutput, pixelCoords, vec4(directLight + (blurredGI * albedo), 1.0));
}